USE [master]
GO
/****** Object:  Database [Entity_local]    Script Date: 12/04/2022 08:15:14 a. m. ******/
CREATE DATABASE [Entity_local]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Entity_local', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Entity_local.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Entity_local_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Entity_local_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Entity_local] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Entity_local].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Entity_local] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Entity_local] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Entity_local] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Entity_local] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Entity_local] SET ARITHABORT OFF 
GO
ALTER DATABASE [Entity_local] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Entity_local] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Entity_local] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Entity_local] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Entity_local] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Entity_local] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Entity_local] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Entity_local] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Entity_local] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Entity_local] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Entity_local] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Entity_local] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Entity_local] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Entity_local] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Entity_local] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Entity_local] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Entity_local] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Entity_local] SET RECOVERY FULL 
GO
ALTER DATABASE [Entity_local] SET  MULTI_USER 
GO
ALTER DATABASE [Entity_local] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Entity_local] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Entity_local] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Entity_local] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Entity_local] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Entity_local] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Entity_local', N'ON'
GO
ALTER DATABASE [Entity_local] SET QUERY_STORE = OFF
GO
USE [Entity_local]
GO
/****** Object:  Table [dbo].[destinos]    Script Date: 12/04/2022 08:15:14 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[destinos](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[foto] [varchar](50) NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[descripcion] [varchar](50) NOT NULL,
	[precio] [varchar](50) NOT NULL
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Entity_local] SET  READ_WRITE 
GO
